---
  - name: "Checking To See If Fix Is In Place"
    ansible.builtin.shell:
      cmd: "cat /boot/cmdline.txt"
      executable: /bin/bash
    register: alsa_fix_check
  - name: "Appending Alsa Fix To /boot/cmdline.txt"
    ansible.builtin.shell:
      cmd: "sed -i '1 s/$/ snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_compat_alsa=1/' /boot/cmdline.txt"
      executable: /bin/bash
    when: alsa_fix_check.stdout.find('snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 snd_bcm2835.enable_compat_alsa=1') == -1
