---
  - name: "Ensuring /home/pi/.ssh Exists"
    ansible.builtin.file:
      path: "/home/pi/.ssh"
      owner: pi
      group: pi
      mode: '0700'
      state: directory
  - name: "Deploying Personal SSH Key To Pi User"
    ansible.builtin.copy:
      src: "{{ authorized_key_file }}"
      dest: "/home/pi/.ssh/authorized_keys"
      owner: pi
      group: pi
      mode: '0600'
